---
- name: Hosts setup 
  hosts: all
  become: true
  vars:
    - fqdn: lab.example.com
    - hostname: "{{ ansible_hostname }}.{{ fqdn }}"
  tasks:
  - name: Setting Hostname
    hostname: 
      name: "{{ hostname }}"
  - name: Creating User Account
    user:
      name: user
      shell: /bin/bash
      groups: wheel
      append: yes
  - name: Changing User Password
    shell: echo password | sudo passwd user --stdin
  - name: Changing Root Password
    shell: echo password | sudo passwd root --stdin
  - name: Adjusting services
    selinux:
      state: permissive
      policy: targeted
  - name: Building Host File
    template: 
      src: hosts.j2 
      dest: /etc/hosts
  - name: Erasing Repos
    file: 
      path: /etc/yum.repos.d/*
      state: absent
  - name: Creating Temporary Repo File
    file:
      path: /etc/yum.repos.d/local.repo
      state: touch
      mode: 0755
  - name: Building Repo File
    copy:
      dest: /etc/yum.repos.d/local.repo
      content: "[base]\nname=Base\nbaseurl=http://repo/BaseOS\ngpgcheck=0\nenabled=1\n\n[apps]\nname=Apps\nbaseurl=http://repo/AppStream\ngpgcheck=0\nenabled=1"
      force: yes
  - name: Enabling IPV6
    sysctl:
      name: "{{ item }}"
      value: '0'
      sysctl_set: yes
    with_items:
      - net.ipv6.conf.lo.disable_ipv6
      - net.ipv6.conf.all.disable_ipv6
  - name: Environment Packages Installed.
    yum: name=man-pages state=present 
    register: yum_sleeper
  - name: Starting services
    service: name=firewalld enabled=true state=started
  - name: Fixing Resolv File
    lineinfile:
      path: /etc/resolv.conf
      line: 'nameserver 8.8.8.8'
      state: present
  - name: Welcome to the RHCE 8 Study/Test Environment!
    debug:
      msg:
        - 'Next Steps: Accessing The Systems:'
        - '- Control - 172.25.250.9'
        - '- Server a - 172.25.250.10'
        - '- Server b - 172.25.250.11'
        - '- Server c - 172.25.250.12'
        - '- Server d - 172.25.250.13'
        - '- Username/Password - user/password'
        - '--------------------------------------------------'
        - '- For root - use `sudo` or `sudo su`'
        - '- Access example - ssh user@172.25.250.9'
        - '- Happy Studying!'
